exclude_paths:
  - db/migrate

detectors:
  IrresponsibleModule:
    enabled: false

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyStatements:
      max_statements: 10
  "app/controllers/concerns":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/models/concerns":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
