# frozen_string_literal: true
class User < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include Clearance::User
  include UserTrackable

  # relationships .............................................................
  belongs_to :person
  has_many :organization_users, dependent: :destroy
  has_many :organizations, through: :organization_users

  # validations ...............................................................
  # callbacks .................................................................

  # scopes ....................................................................
  default_scope { order(last_name: :asc, first_name: :asc) }

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  has_person_name

  # class methods .............................................................
  # public instance methods ...................................................
  def display_name
    name.familiar
  end

  def member_of?(organization)
    organization.in?(organizations)
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
